### PR TITLE
arcpy.mapping edits

### PR DESCRIPTION
**Pull request by amyns**
Reordering and editing (incomplete)

### CODE REVIEW

**Comment by amyns** [comment]
I restructured my sections quite a bit, but wasn't using the _extended version.  Not sure how to work on combining the notebooks.

**Comment by Dave-Evans** [comment]
Hey Allison,
I should I have mentioned which I was going to be using, but hey I don't think its an issue. I just merged the files together and now it seems that all of our changes are there together! I will switch to the NON extended version from now on. 
All the best,

Dave

**Comment by amyns** [comment]
Thanks!  I'll see if I can figure out how to "pull" the merged file. :)

I'm definitely going to need to add 2 feature classes to the geodatabase, and I'll have a different .mxd than Larry was using, but I haven't got it all worked out yet.

For the class, I'd like to hide the outputs and "play" those from iPython Notebook as we go through the course.  Is that what you were thinking?  I'll also have a bit that I'll need to run in ArcMap.  

-Alison

---

On Sat, 2/7/15, Dave-Evans notifications@github.com wrote:

 Subject: Re: [pythonGisWorkshop] arcpy.mapping edits (#1)
 To: "Dave-Evans/pythonGisWorkshop" pythonGisWorkshop@noreply.github.com
 Cc: "amyns" a1myns0117-01@yahoo.com
 Date: Saturday, February 7, 2015, 12:30 PM

 Hey Allison,

 I should I have mentioned which I was going to be using, but
 hey I don't think its an issue. I just merged the files
 together and now it seems that all of our changes are there
 together! I will switch to the NON extended version from now
 on. 

 All the best,

 Dave 

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by amyns** [comment]
Hi Dave,

Are you going over methods/functions?  I think I'm supposed to go over objects, but I'm not sure how to put it in context without just adding confusion, unless I contrast it with methods or something.

## -Alison

On Sat, 2/7/15, Dave-Evans notifications@github.com wrote:

 Subject: Re: [pythonGisWorkshop] arcpy.mapping edits (#1)
 To: "Dave-Evans/pythonGisWorkshop" pythonGisWorkshop@noreply.github.com
 Cc: "amyns" a1myns0117-01@yahoo.com
 Date: Saturday, February 7, 2015, 12:30 PM

 Hey Allison,

 I should I have mentioned which I was going to be using, but
 hey I don't think its an issue. I just merged the files
 together and now it seems that all of our changes are there
 together! I will switch to the NON extended version from now
 on. 

 All the best,

 Dave 

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by amyns** [comment]
Hi Dave,

I actually lost a bunch of my changes in that merge, so I'm going to work separately on my sections.

## -Alison

On Sat, 2/7/15, Dave-Evans notifications@github.com wrote:

 Subject: Re: [pythonGisWorkshop] arcpy.mapping edits (#1)
 To: "Dave-Evans/pythonGisWorkshop" pythonGisWorkshop@noreply.github.com
 Cc: "amyns" a1myns0117-01@yahoo.com
 Date: Saturday, February 7, 2015, 12:30 PM

 Hey Allison,

 I should I have mentioned which I was going to be using, but
 hey I don't think its an issue. I just merged the files
 together and now it seems that all of our changes are there
 together! I will switch to the NON extended version from now
 on. 

 All the best,

 Dave 

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by Dave-Evans** [comment]
Crap, I'm so sorry that didn't work. Did you have to redo a bunch of work? I'm sorry I"m still getting the hang of git.

**Pull request merged**
